name_set = set()
name_set.add("Alice")
name_set.add("Bob")
name_set.add("Charlie")
name_set.add("David")
name_set.add("Eva")
print("Set after adding names:", name_set)
name_set.remove("Bob")  
name_set.add("Bobby")   
print("Set after modifying a name:", name_set)
name_set.remove("Charlie")  
name_set.remove("David")    
print("Set after deleting names:", name_set)
